
export default {
	name: "siteSettings",
	type: "document",
	title: "Site configuration",
	groups: [
		{
			name: "seo",
			title: "SEO",
		},
		{
			name: "intro",
			title: "Intro",
		},
		{
			name: "tweede_blok",
			title: "Tweede blok",
		},
		{
			name: "approach",
			title: "approach",
		},
		{
			name: "services",
			title: "services",
		},
		{
			name: "team",
			title: "team",
		},
		{
			name: "why_function",
			title: "why function",
		},
		{
			name: "partners",
			title: "partners",
		},
		{
			name: "contact",
			title: "contact",
		},
		{
			name: "application_process",
			title: "application process",
		},
		{
			name: "career",
			title: "career",
		},
		{
			name: "mindset",
			title: "mindset",
		},
	],
	fields: [
		{
			name: "meta_title",
			title: "Meta title",
			type: "string",
			group: "seo",
		},
		{
			name: "meta_description",
			title: "Meta Description",
			type: "string",
			group: "seo",
		},
		{
			name: "title",
			title: "Intro title",
			type: "string",
			group: "intro",
		},
		{
			name: "list_left",
			title: "Opsomming links",
			type: "array",
			of: [{ type: "string" }],
			group: "intro",
		},
		{
			name: "list_right",
			title: "Opsomming rechts",
			type: "array",
			of: [{ type: "string" }],
			group: "intro",
		},
		{
			name: "titel_tweede_blok",
			title: "Titel voor groene blob",
			type: "string",
			group: "tweede_blok",
		},
		{
			name: "titel_tweede_blok_blob",
			title: "Titel in groene blob",
			type: "string",
			group: "tweede_blok",
		},
		{
			name: "beschrijving_tweede_blok_blob",
			title: "Tekst in beschrijving in groene blob",
			type: "string",
			group: "tweede_blok",
		},
		{
			name: "beschrijving_tweede_blok",
			title: "Tekst in beschrijving na groene blob",
			type: "text",
			group: "tweede_blok",
		},
		{
			name: "partner_titel_tweede_blok",
			title: "Partner titel in tweede blok",
			type: "text",
			group: "tweede_blok",
		},
		{
			name: "clients_tweede_blok",
			title: "Klanten in tweede blok",
			type: "array",
			of: [{ type: "reference", to: { type: "client" } }],
			group: "tweede_blok",
		},
		{
			name: "navigation_tweede_blok",
			title: "Navigatie tweede blok",
			type: "string",
			group: "tweede_blok",
		},
		{
			name: "approach_title",
			title: "Approach title",
			type: "string",
			group: "approach",
		},
		{
			name: "approach_text",
			title: "Approach text",
			type: "string",
			group: "approach",
		},
		{
			name: "approach_navigation_1_title",
			title: "Approach navigation 1 title",
			type: "string",
			group: "approach",
		},
		{
			name: "approach_navigation_2_title",
			title: "Approach navigation 2 title",
			type: "string",
			group: "approach",
		},
		{
			name: "approach_navigation_3_title",
			title: "Approach navigation 3 title",
			type: "string",
			group: "approach",
		},
		{
			name: "approach_navigation_3_text",
			title: "Approach navigation 3 text",
			type: "string",
			group: "approach",
		},
		{
			name: "services_title",
			title: "services title",
			type: "string",
			group: "services",
		},
		{
			name: "services_text",
			title: "services text",
			type: "string",
			group: "services",
		},
		{
			name: "services_slide_1_title",
			title: "services slide 1 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_slide_1_text",
			title: "services slide 1 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_slide_2_title",
			title: "services slide 2 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_slide_2_text",
			title: "services slide 2 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_slide_3_title",
			title: "services slide 3 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_slide_3_text",
			title: "services slide 3 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_slide_4_title",
			title: "services slide 4 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_slide_4_text",
			title: "services slide 4 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_slide_5_title",
			title: "services slide 5 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_slide_5_text",
			title: "services slide 5 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_accordion_1_title",
			title: "services accordion 1 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_accordion_1_text",
			title: "services accordion 1 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_accordion_2_title",
			title: "services accordion 2 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_accordion_2_text",
			title: "services accordion 2 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_accordion_3_title",
			title: "services accordion 3 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_accordion_3_text",
			title: "services accordion 3 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_accordion_4_title",
			title: "services accordion 4 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_accordion_4_text",
			title: "services accordion 4 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_accordion_5_title",
			title: "services accordion 5 title",
			type: "string",
			group: "services",
		},
		{
			name: "services_accordion_5_text",
			title: "services accordion 5 text",
			type: "text",
			group: "services",
		},
		{
			name: "services_navigation_title",
			title: "services navigation title",
			type: "string",
			group: "services",
		},
		{
			name: "services_technologies_title",
			title: "services technologies title",
			type: "string",
			group: "services",
		},
		{
			name: "services_partners",
			title: "partners in service blok",
			type: "array",
			of: [{ type: "reference", to: { type: "partner" } }],
			group: "services",
		},
		{
			name: "team_title",
			title: "team title",
			type: "string",
			group: "team",
		},
		{
			name: "team_text",
			title: "team text",
			type: "string",
			group: "team",
		},
		{
			name: "team_nav_title",
			title: "team navigation title",
			type: "string",
			group: "team",
		},
		{
			name: "why_function_title",
			title: "why function title",
			type: "string",
			group: "why_function",
		},
		{
			name: "why_function_text",
			title: "why function text",
			type: "string",
			group: "why_function",
		},
		{
			name: "partners_title",
			title: "partners title",
			type: "string",
			group: "partners",
		},
		{
			name: "partners_text",
			title: "partners text",
			type: "string",
			group: "partners",
		},
		{
			name: "locatie",
			title: "Locatie",
			type: "geopoint",
			group: "contact",
		},
		{
			name: "adres",
			title: "adres",
			type: "text",
			group: "contact",
		},
		{
			name: "telefoon",
			title: "telefoon",
			type: "string",
			group: "contact",
		},
		{
			name: "email",
			title: "email",
			type: "string",
			group: "contact",
		},

		{
			name: "steps",
			title: "steps",
			type: "array",
			of: [
				{
					type: "object",
					fields: [
						{
							name: "title",
							title: "title",
							type: "string",
						},
						{
							name: "content",
							title: "content",
							type: "text",
						},
					],
				},
			],
			group: "application_process",
		},
		{
			name: "partner_title",
			title: "partner title",
			type: "string",
			group: "application_process",
		},
		{
			name: "partner_subtitle",
			title: "partner subtitle",
			type: "string",
			group: "application_process",
		},
		{
			name: "partner_learning_agreement",
			title: "partner learning agreement",
			type: "string",
			group: "application_process",
		},
		{
			name: "years",
			title: "years",
			type: "array",
			of: [
				{
					type: "object",
					fields: [
						{
							name: "year",
							title: "year",
							type: "string",
						},
						{
							name: "content",
							title: "content",
							type: "text",
						},
					],
				},
			],
			group: "application_process",
		},
		{
			name: "career_title",
			title: "career title",
			type: "string",
			group: "career",
		},
		{
			name: "career_text",
			title: "career text",
			type: "text",
			group: "career",
		},
		{
			name: "career_text_small",
			title: "career text small",
			type: "text",
			group: "career",
		},
		{
			name: "career_list",
			title: "career list",
			type: "array",
			of: [{ type: "string", title: "list item", name: "list_item" }],
			group: "career",
		},
		{
			name: "mindset_title",
			title: "mindset title",
			type: "string",
			group: "mindset",
		},
		{
			name: "mindset_subtitle",
			title: "mindset subtitle",
			type: "string",
			group: "mindset",
		},
		{
			name: "mindset_slide_1_title",
			title: "mindset slide 1 title",
			type: "string",
			group: "mindset",
		},
		{
			name: "mindset_slide_1_text",
			title: "mindset slide 1 text",
			type: "text",
			group: "mindset",
		},
		{
			name: "mindset_slide_2_title",
			title: "mindset slide 2 title",
			type: "string",
			group: "mindset",
		},
		{
			name: "mindset_slide_2_text",
			title: "mindset slide 2 text",
			type: "text",
			group: "mindset",
		},
		{
			name: "mindset_whitepaper_title",
			title: "mindset whitepaper title",
			type: "string",
			group: "mindset",
		},
		{
			name: "mindset_whitepaper_subtitle",
			title: "mindset whitepaper subtitle",
			type: "string",
			group: "mindset",
		},
		{
			name: "mindset_whitepaper_cta",
			title: "mindset whitepaper cta",
			type: "string",
			group: "mindset",
		},
	],
};